extends Node
# 统一音频服务，集中管理音量总线和程序化音效播放。
class_name AudioManagerService

const BUS_PARENT: Dictionary = {
	"Master": "",
	"Music": "Master",
	"SFX": "Master",
	"UI": "Master",
}

# Per-scene BGM tracks (paths are res:// resources baked into the web pck).
# Each scene picks one based on its key. Keep this list in sync with the
# WAV files generated by scripts/audio/build_bgm.py.
const BGM_TRACKS: Dictionary = {
	"menu":          "res://assets/audio/bgm_menu.wav",
	"match_start":   "res://assets/audio/bgm_match_start.wav",
	"match_end":     "res://assets/audio/bgm_match_end.wav",
	"arena_cross":   "res://assets/audio/bgm_arena_cross.wav",
	"neon_docks":    "res://assets/audio/bgm_neon_docks.wav",
	"reactor_ring":  "res://assets/audio/bgm_reactor_ring.wav",
	"skyline_yard":  "res://assets/audio/bgm_skyline_yard.wav",
}

# Map config.map_id → BGM key. Mirrors the constants in scripts/config/match_config.gd.
const MAP_BGM_KEY: Dictionary = {
	"arena_cross":  "arena_cross",
	"neon_docks":   "neon_docks",
	"reactor_ring": "reactor_ring",
	"skyline_yard": "skyline_yard",
}

const EVENT_PROFILES: Dictionary = {
	"shoot": {"freq": 560.0, "end_freq": 310.0, "duration": 0.075, "volume": 0.20, "bus": "SFX", "noise": 0.12},
	"empty": {"freq": 210.0, "end_freq": 180.0, "duration": 0.060, "volume": 0.12, "bus": "SFX", "noise": 0.05},
	"impact": {"freq": 140.0, "end_freq": 90.0, "duration": 0.095, "volume": 0.16, "bus": "SFX", "noise": 0.28},
	"hit": {"freq": 320.0, "end_freq": 190.0, "duration": 0.105, "volume": 0.18, "bus": "SFX", "noise": 0.18},
	"death": {"freq": 180.0, "end_freq": 70.0, "duration": 0.180, "volume": 0.19, "bus": "SFX", "noise": 0.20},
	"respawn": {"freq": 410.0, "end_freq": 760.0, "duration": 0.170, "volume": 0.14, "bus": "SFX", "noise": 0.04},
	"dash": {"freq": 260.0, "end_freq": 520.0, "duration": 0.085, "volume": 0.12, "bus": "SFX", "noise": 0.16},
	"shield": {"freq": 360.0, "end_freq": 260.0, "duration": 0.120, "volume": 0.13, "bus": "SFX", "noise": 0.03},
	"pickup": {"freq": 580.0, "end_freq": 860.0, "duration": 0.110, "volume": 0.12, "bus": "SFX", "noise": 0.02},
	"pulse": {"freq": 180.0, "end_freq": 520.0, "duration": 0.150, "volume": 0.16, "bus": "SFX", "noise": 0.16},
	"ui_click": {"freq": 520.0, "end_freq": 650.0, "duration": 0.045, "volume": 0.10, "bus": "UI", "noise": 0.00},
	"ui_hover": {"freq": 360.0, "end_freq": 390.0, "duration": 0.030, "volume": 0.055, "bus": "UI", "noise": 0.00},
}

var tone_rng := RandomNumberGenerator.new()
var runtime_audio_enabled: bool = true

# Background music playback. A single looping AudioStreamPlayer on the Music
# bus is reused across scene changes; play_bgm(key) swaps its stream.
var _bgm_player: AudioStreamPlayer
var _bgm_fade_tween: Tween

# HTML5 browsers block audio until the first user gesture (autoplay policy).
# AudioManager listens for any mouse/key event and flips _audio_unlocked; any
# play_bgm call that arrived before that gets queued and fired here.
var _audio_unlocked: bool = false
var _pending_bgm_key: String = ""

func _ready() -> void:
	tone_rng.seed = 9917
	ensure_bus_layout()
	_ensure_bgm_player()
	set_process_unhandled_input(true)

func _unhandled_input(event: InputEvent) -> void:
	# First user interaction of any kind unlocks the AudioContext in HTML5.
	if _audio_unlocked:
		return
	var is_click: bool = event is InputEventMouseButton and event.pressed
	var is_key: bool = event is InputEventKey and event.pressed and not event.echo
	var is_touch: bool = event is InputEventScreenTouch and event.pressed
	if is_click or is_key or is_touch:
		unlock_audio()

func unlock_audio() -> void:
	# Called automatically on first user input (above) or manually from a scene.
	if _audio_unlocked:
		return
	_audio_unlocked = true
	var pending := _pending_bgm_key
	_pending_bgm_key = ""
	if not pending.is_empty():
		play_bgm(pending, 0.0)

func is_audio_unlocked() -> bool:
	return _audio_unlocked

func _ensure_bgm_player() -> void:
	if _bgm_player != null and is_instance_valid(_bgm_player):
		return
	_bgm_player = AudioStreamPlayer.new()
	_bgm_player.bus = "Music"
	_bgm_player.volume_db = linear_to_db(0.9)
	add_child(_bgm_player)

func ensure_bus_layout() -> void:
	for bus_name in BUS_PARENT.keys():
		_ensure_bus(bus_name, BUS_PARENT[bus_name])

func apply_volume_settings(audio_settings: Dictionary) -> void:
	_set_bus_volume("Master", float(audio_settings.get("master", 0.8)))
	_set_bus_volume("SFX", float(audio_settings.get("sfx", 0.85)))
	_set_bus_volume("Music", float(audio_settings.get("music", 0.55)))

func set_runtime_audio_enabled(enabled: bool) -> void:
	runtime_audio_enabled = enabled

func play_event(event_name: String, position: Vector2 = Vector2.ZERO) -> void:
	if not is_inside_tree():
		return
	if not runtime_audio_enabled:
		return
	if DisplayServer.get_name().to_lower() == "headless":
		return
	var profile: Dictionary = EVENT_PROFILES.get(event_name, EVENT_PROFILES.get("impact", {}))
	if profile.is_empty():
		return
	_play_generated_tone(profile)
	AppLog.debug("Audio event", {"event": event_name, "position": position})

func play_bgm(key: String, fade_seconds: float = 0.4) -> void:
	# Switch the looping music player to the track for the given scene key.
	# Pass an empty string (or "none") to stop playback cleanly.
	if not is_inside_tree():
		return
	if DisplayServer.get_name().to_lower() == "headless":
		return
	# Defer until the first user interaction in HTML5 (browser autoplay policy).
	if DisplayServer.get_name().to_lower() == "web" and not _audio_unlocked:
		_pending_bgm_key = key
		return
	_ensure_bgm_player()
	if key.is_empty() or key == "none":
		stop_bgm(fade_seconds)
		return
	if not BGM_TRACKS.has(key):
		AppLog.warn("Unknown BGM key", {"key": key})
		return
	var stream_path: String = BGM_TRACKS[key]
	if not ResourceLoader.exists(stream_path):
		AppLog.warn("BGM asset missing", {"key": key, "path": stream_path})
		return
	var stream: AudioStream = load(stream_path)
	if stream == null:
		return
	# Avoid restarting if the same track is already playing.
	if _bgm_player.playing and _bgm_player.stream == stream:
		return
	_fade_bgm(fade_seconds, 0.0, func() -> void:
		_bgm_player.stream = stream
		if stream is AudioStreamWAV:
			(stream as AudioStreamWAV).loop_mode = AudioStreamWAV.LOOP_FORWARD
		_bgm_player.play()
		_fade_bgm(fade_seconds, 1.0, null)
	)

func stop_bgm(fade_seconds: float = 0.3) -> void:
	if _bgm_player == null or not is_instance_valid(_bgm_player):
		return
	if not _bgm_player.playing:
		return
	_fade_bgm(fade_seconds, 0.0, func() -> void:
		if _bgm_player != null and is_instance_valid(_bgm_player):
			_bgm_player.stop()
	)

func _fade_bgm(seconds: float, target_volume: float, on_complete: Variant) -> void:
	if _bgm_player == null or not is_instance_valid(_bgm_player):
		return
	if _bgm_fade_tween != null and _bgm_fade_tween.is_valid():
		_bgm_fade_tween.kill()
	if seconds <= 0.0:
		_bgm_player.volume_db = linear_to_db(0.6 * clampf(target_volume, 0.0, 1.0))
		if on_complete is Callable and on_complete.is_valid():
			on_complete.call()
		return
	_bgm_fade_tween = create_tween()
	_bgm_fade_tween.tween_property(_bgm_player, "volume_db", linear_to_db(0.6 * clampf(target_volume, 0.0, 1.0)), seconds)
	if on_complete is Callable and on_complete.is_valid():
		_bgm_fade_tween.tween_callback(on_complete)

func _ensure_bus(bus_name: String, parent_bus: String) -> void:
	if AudioServer.get_bus_index(bus_name) >= 0:
		return
	var idx := AudioServer.bus_count
	AudioServer.add_bus(idx)
	AudioServer.set_bus_name(idx, bus_name)
	AudioServer.set_bus_send(idx, parent_bus)

func _set_bus_volume(bus_name: String, linear_value: float) -> void:
	var idx := AudioServer.get_bus_index(bus_name)
	if idx < 0:
		return
	var clamped := clampf(linear_value, 0.0, 1.0)
	AudioServer.set_bus_volume_db(idx, linear_to_db(clamped) if clamped > 0.001 else -80.0)

func _play_generated_tone(profile: Dictionary) -> void:
	var duration := float(profile.get("duration", 0.08))
	var mix_rate := 22050.0
	var stream := AudioStreamGenerator.new()
	stream.mix_rate = mix_rate
	stream.buffer_length = duration + 0.04
	var player := AudioStreamPlayer.new()
	player.stream = stream
	player.bus = str(profile.get("bus", "SFX"))
	add_child(player)
	player.play()
	var playback := player.get_stream_playback() as AudioStreamGeneratorPlayback
	if playback == null:
		player.queue_free()
		return
	var frames := int(duration * mix_rate)
	var start_freq := float(profile.get("freq", 440.0))
	var end_freq := float(profile.get("end_freq", start_freq))
	var volume := float(profile.get("volume", 0.12))
	var noise := float(profile.get("noise", 0.0))
	var phase := 0.0
	for i in range(frames):
		var t := float(i) / float(maxi(frames - 1, 1))
		var freq := lerpf(start_freq, end_freq, t)
		phase += TAU * freq / mix_rate
		var envelope := pow(1.0 - t, 1.8)
		var sample := sin(phase) * volume * envelope
		if noise > 0.0:
			sample += tone_rng.randf_range(-noise, noise) * volume * envelope
		playback.push_frame(Vector2(sample, sample))
	get_tree().create_timer(duration + 0.08, true).timeout.connect(player.queue_free)
